#! /usr/bin/bash


DB_ROOT=$(pwd)/databases
mkdir -p "$DB_ROOT"


function create_db() {
   read -p "Enter database name: " db
mkdir "$DB_ROOT/$db" 2>/dev/null && echo "Database created" || echo "Database exists"
}

function list_db() {
echo "Databases:"
ls "$DB_ROOT"
}


function main_menu() {
    select choice in "Create DB" "List DB" "Exit"
    do
        case $choice in
            "Create DB") create_db ;;
            "List DB") list_db ;;
            "Exit") exit ;;
            *) echo "Invalid choice" ;;
        esac
    done
}

main_menu



