#! /usr/bin/bash
shopt -s extglob


function table_menu() {
    select choice in "Create Table" "Back"
    do
        case $choice in
            "Create Table") create_table ;;

            "Back") break ;;
        esac
    done
}

 
function create_table() {
  
  if [ -z "$dbname" ]; then
    echo "No database selected"
    return
  fi

  read -p "Enter table name: " table

  touch "$table"
 
   touch "${table}_meta"
 
  echo "Table created"
}
