#! /usr/bin/bash
shopt -s extglob
 
 source tables/creatingtable
source tables/listingtable
function table_menu() {
 PS3="Your choice here  : " 
    select choice in "Create Table" "list Tables"   "Back"
    do
        case $choice in
            "Create Table") create_table ;;
             "list Tables") list_tables ;;
            "Back") break ;;
        esac
    done
}

